POST http://127.0.0.1:5000/api/room
Content-Type: application/json

{
    "name": "Room24"
}
###

PATCH  http://127.0.0.1:5000/api/room
Content-Type: application/json

{
    "where": { "id": 20 },
    "data": { "name": "Rename Room 20"}
}
###


DELETE   http://127.0.0.1:5000/api/room
Content-Type: application/json

{
    "where": { "id": 25 }
}
###

GET   http://127.0.0.1:5000/api/rooms
###

POST http://127.0.0.1:5000/api/room/user
Content-Type: application/json

{
    "id": 24,
    "userId": 5
}
###

DELETE  http://127.0.0.1:5000/api/room/user
Content-Type: application/json

{
    "id": 24,
    "userId": 4
}
###


POST http://127.0.0.1:5000/api/room/admin
Content-Type: application/json

{
    "id": 24,
    "adminId": 3
}
###

DELETE  http://127.0.0.1:5000/api/room/admin
Content-Type: application/json

{
    "id": 24,
    "adminId": 3
}
###